### ISSUE TITLE
NO Readme

### ISSUE THREAD

**Issue by priyam-tongia** [mzagane/ZM_Source_Code_Metrics#1]
Can you make a proper Readme File? I'm not able to understand where should I give my input file and what other things I've to change.

**Comment by mzagane** [comment]
Sorry about that, indeed in this version Command-line arguments not yet implemented. 

You have to define yours inputs  (two parameters) directly in the source code (main file: ZM_Source_Code_Metrics.cpp).

The two parameters to define are:

1 ) the path of the directory which contains the source codes for which we want to calculate the metrics, (the variable: std :: string Project_Dir = "path_to_your_files";),

2) the path of the programming language file (a configuration language file (.lng) specific to the programming language (c, c ++, ...) of your source), these files are included in the "languages" directory.

**Comment by priyam-tongia** [comment]
While following the above steps and also while using your and mine test cases I got the following errors. Can you update it in your code or help me out in debugging?
![error](https://user-images.githubusercontent.com/63399260/81309064-277ea600-90a0-11ea-974f-624cd56b8d01.JPG)

**Comment by mzagane** [comment]
the MinGW version of dirent is simplified. the d_type field is no longer available. so if you compile using MinGW it gives that error.
I use the "d_type" field to find out the type (file, folder) of the entry, as a workaround:
instead of testing like:
  if (Dirent-> d_type! = DT_DIR)
{
     // add the file
}
we can test as follow:
DIR * TEMP;
if ((TEMP = opendir (Dirent-> d_name)))
{
                 closedir (TEMP);
}
else
{
         // add the file
}

Code updated, Normally now it works

**Comment by mzagane** [comment]
- Command-line arguments implemented,
- Issues with MinGW fixed
